export const BOOK_CATEGORY = [
  { category_id: 101, category_name: "소설" },
  { category_id: 102, category_name: "시·에세이" },
  { category_id: 103, category_name: "예술·대중문화" },
  { category_id: 104, category_name: "사회과학" },
  { category_id: 105, category_name: "역사와 문화" },
  { category_id: 107, category_name: "잡지" },
  { category_id: 108, category_name: "만화" },
  { category_id: 109, category_name: "유아" },
  { category_id: 110, category_name: "아동" },
  { category_id: 111, category_name: "가정과 생활" },
  { category_id: 112, category_name: "청소년" },
  { category_id: 113, category_name: "초등학습서" },
  { category_id: 114, category_name: "고등학습서" },
  { category_id: 115, category_name: "국어·외국어·사전" },
  { category_id: 116, category_name: "자연과 과학" },
  { category_id: 117, category_name: "경제경영" },
  { category_id: 118, category_name: "자기계발" },
  { category_id: 119, category_name: "인문" },
  { category_id: 120, category_name: "종교·역학" },
  { category_id: 122, category_name: "컴퓨터·인터넷" },
  { category_id: 123, category_name: "자격서·수험서" },
  { category_id: 124, category_name: "취미·레저" },
  { category_id: 125, category_name: "전공도서·대학교재" },
  { category_id: 126, category_name: "건강·뷰티" },
  { category_id: 128, category_name: "여행" },
  { category_id: 129, category_name: "중등학습서" },
  { category_id: 201, category_name: "어린이" },
  { category_id: 203, category_name: "ELT·사전" },
  { category_id: 205, category_name: "문학" },
  { category_id: 206, category_name: "경영·인문" },
  { category_id: 207, category_name: "예술·디자인" },
  { category_id: 208, category_name: "실용" },
  { category_id: 209, category_name: "해외잡지" },
  { category_id: 210, category_name: "대학교재·전문서적" },
  { category_id: 211, category_name: "컴퓨터" },
  { category_id: 214, category_name: "일본도서" },
  { category_id: 215, category_name: "프랑스도서" },
  { category_id: 216, category_name: "중국도서" },
];
